### ISSUE TITLE
Questions about training the llff_downX script   

### ISSUE THREAD

**Issue by XLR-man** [cwchenwang/NeRF-SR#7]
In the llff_downX script, it says: if downscale=4, change batchsize=128.

But when I do, I get an error:
```
Traceback (most recent call last):
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/einops/einops.py", line 412, in reduce
    return _apply_recipe(recipe, tensor, reduction_type=reduction)
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/einops/einops.py", line 235, in _apply_recipe
    _reconstruct_from_shape(recipe, backend.shape(tensor))
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/einops/einops.py", line 200, in _reconstruct_from_shape_uncached
    raise EinopsError("Shape mismatch, can't divide axis of length {} in chunks of {}".format(
einops.EinopsError: Shape mismatch, can't divide axis of length 378 in chunks of 4

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 163, in <module>
    run_dp()
  File "train.py", line 152, in run_dp
    main(None)
  File "train.py", line 38, in main
    dataset = create_dataset(opt, mode=opt.train_split, shuffle=True)  # create a dataset given opt.dataset_mode and other options
  File "/root/autodl-tmp/data/__init__.py", line 78, in create_dataset
    data_loader = CustomDatasetDataLoader(opt, mode, shuffle)
  File "/root/autodl-tmp/data/__init__.py", line 105, in __init__
    self.dataset = dataset_class(opt, mode)
  File "/root/autodl-tmp/data/llff_downX_dataset.py", line 193, in __init__
    self.read_meta()
  File "/root/autodl-tmp/data/llff_downX_dataset.py", line 329, in read_meta
    img = einops.rearrange(img, '(h s1) (w s2) c -> (h w) (s1 s2) c', 
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/einops/einops.py", line 483, in rearrange
    return reduce(cast(Tensor, tensor), pattern, reduction='rearrange', **axes_lengths)
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/einops/einops.py", line 420, in reduce
    raise EinopsError(message + '\n {}'.format(e))
einops.EinopsError:  Error while processing rearrange-reduction pattern "(h s1) (w s2) c -> (h w) (s1 s2) c".
 Input tensor shape: torch.Size([378, 504, 3]). Additional info: {'s1': 4, 's2': 4}.
 Shape mismatch, can't divide axis of length 378 in chunks of 4
```

What should I do to make it work?

**Comment by cwchenwang** [comment]
You should set W=1008 and H=756 when setting downscale=4

**Comment by XLR-man** [comment]
Thank you,it works!
But I also ran into a problem. After I trained the supersampling model, I wanted to further train the refine model. It looks like the code needs the 30_val_vis obtained from the former model. But when I run the refine model training code, I get an error:
```
Traceback (most recent call last):
  File "train_refine.py", line 147, in <module>
    run_dp()
  File "train_refine.py", line 136, in run_dp
    main(None)
  File "train_refine.py", line 40, in main
    dataset_val = create_dataset(opt, mode=opt.val_epoch_split, shuffle=False)
  File "/root/autodl-tmp/data/__init__.py", line 78, in create_dataset
    data_loader = CustomDatasetDataLoader(opt, mode, shuffle)
  File "/root/autodl-tmp/data/__init__.py", line 105, in __init__
    self.dataset = dataset_class(opt, mode)
  File "/root/autodl-tmp/data/llff_refine_dataset.py", line 48, in __init__
    self.read_meta()
  File "/root/autodl-tmp/data/llff_refine_dataset.py", line 176, in read_meta
    loc = np.load(os.path.join(self.opt.syn_dataroot, '{}_locs.npz'.format(i)))['arr_0']
  File "/root/miniconda3/envs/py38/lib/python3.8/site-packages/numpy/lib/npyio.py", line 405, in load
    fid = stack.enter_context(open(os_fspath(file), "rb"))
FileNotFoundError: [Errno 2] No such file or directory: './checkpoints/nerf-sr/llff-horns-378x504-ni64-dp-ds2/30_val_vis/0_locs.npz'
```
When I checked the corresponding folder generated by my training code, there was no npz file. In turn, this file exists in the file you provide with the pre-trained model. So I'm a little confused. I didn't include any parameters in the model training to generate this file. Look forward to your answer.

Also you gave llff the pre-trained model without refine_x4 model and blender without x4 model. Can you provide these missing pre-trained models? Since I find the training time required for x4 models to take a long time (which feels like one of the shortcomings of this model), I would be able to investigate further if you could provide these missing pre-trained models

**Comment by cwchenwang** [comment]
You have to run `python warp.py` to get the .loc file. More details can be found in the README.
